export const TYPES = {
    Logger: Symbol.for('Logger'),
    IDatabaseService: Symbol.for('IDatabaseService'),
    IAuthRepository: Symbol.for('IAuthRepository'),
    IAuthService: Symbol.for('IAuthService'),
    IUserRepository: Symbol.for('IUserRepository'),
    IUserService: Symbol.for('IUserService'),
    IJsonWebTokenService: Symbol.for('IJsonWebTokenService'),
    AuthenticationMiddleware: Symbol.for('AuthenticationMiddleware'),
    IRestaurentRepository: Symbol.for('IRestaurentRepository'),
    IRestaurentService: Symbol.for('IRestaurentService'),
    IItemRepository: Symbol.for('IItemRepository'),
    IItemService: Symbol.for('IItemService'),
    ICartRepository: Symbol.for('ICartRepository'),
    ICartService: Symbol.for('ICartService'),
    IOrderRepository: Symbol.for('IOrderRepository'),
    IOrderService: Symbol.for('IOrderService'),
    ICartSharedRepo: Symbol.for('ICartSharedRepo'),
    IUserSharedRepo: Symbol.for('IUserSharedRepo'),
    IRestaurentSharedRepo: Symbol.for('IRestaurentSharedRepo'),
    IItemSharedRepo: Symbol.for('IItemSharedRepo'),
    IOrderSharedRepository: Symbol.for('IOrderSharedRepository'),
    IElasticsearchService: Symbol.for('IElasticsearchService'),
    IRedisService: Symbol.for('IRedisService'),
};